### ISSUE TITLE
Could you upload EF50L's device & vendor?

### ISSUE THREAD

**Issue by jason-akw** [mifl/android_kernel_pantech_ef50l#1]
Could you upload EF50L's device & vendor?
thank you

**Comment by mifl** [comment]
I only work in the kernel, you can contact with http://tekcafe.vn/, to get the device folders.

**Comment by GeekZJJ** [comment]
@akw28888 Do you get EF50L's device & vendor? Thank you
@mifl The kernel source in this repo works for which Android version? Thanks for you work.

**Comment by mifl** [comment]
@GeekZJJ: The branch caf/LA.AF.1.1.c1 corresponding with this Tag: LA.AF.1.1.c1-01700-8960.0, with this branch you can build Android 05.01.01, see: https://us.codeaurora.org/xwiki/bin/QAEP/release.

For Stock Roms, you must be used the Pantech kernel source.

**Comment by GeekZJJ** [comment]
@mifl Oh,I see, thanks a lot !
